<#
.SYNOPSIS
    Generates a zombie variant of every vanilla combat troop.

.DESCRIPTION
    Reads the vanilla NPCCharacter XMLs from the game installation and writes one
    cloned entry per troop to ModuleData/zombie_troops_generated.xml.

    The clone keeps level, skills, armour, melee weapons and mount so the zombie
    is a 1:1 stand-in for the troop it was made from. Ranged weapons are NOT
    stripped here - that happens at runtime in ZombieTroopSetup, where the game's
    own item data is available (crafted weapons carry no type in the XML).

    Re-run this after a Bannerlord update; the output file is generated, never
    hand-edited.

.EXAMPLE
    pwsh -File tools\Generate-ZombieTroops.ps1
#>
[CmdletBinding()]
param(
    [string] $GameDir = 'E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord',
    [string] $OutFile = (Join-Path $PSScriptRoot '..\ZombiePlague\ModuleData\zombie_troops_generated.xml')
)

$ErrorActionPreference = 'Stop'

# Troops that can realistically end up in a roster the zombies fight. Special,
# Wanderer, Lord and the notable/shopkeeper occupations are left out: they are
# heroes or scenery, not battle troops.
$AllowedOccupations = @(
    'Soldier', 'Bandit', 'CaravanGuard', 'Mercenary', 'Gangster', 'Townsfolk', 'Villager'
)

$SourceFiles = @(
    'Modules\SandBoxCore\ModuleData\spnpccharacters.xml'
    'Modules\SandBox\ModuleData\bandits.xml'
    'Modules\NavalDLC\ModuleData\naval_characters.xml'
)

# A ranged troop without its bow belongs in the shield wall, not the archer line.
$GroupRemap = @{
    'Ranged'      = 'Infantry'
    'HorseArcher' = 'Cavalry'
}

function Get-PlainName {
    param([string] $Raw)
    # "{=JGsUtBT3}Imperial Legionary" -> "Imperial Legionary"
    return ($Raw -replace '^\{=[^}]*\}', '').Trim()
}

$output = New-Object System.Xml.XmlDocument
$declaration = $output.CreateXmlDeclaration('1.0', 'utf-8', $null)
[void] $output.AppendChild($declaration)
[void] $output.AppendChild($output.CreateComment(
    " GENERATED by tools/Generate-ZombieTroops.ps1 - do not edit by hand. "))
$root = $output.CreateElement('NPCCharacters')
[void] $output.AppendChild($root)

$skipped = 0
# Ordered so the output stays stable between runs; keyed so a troop redefined in a
# later module overrides the earlier one, matching how the game merges these files.
$byId = New-Object 'System.Collections.Specialized.OrderedDictionary'

foreach ($relative in $SourceFiles) {
    $path = Join-Path $GameDir $relative
    if (-not (Test-Path -LiteralPath $path)) {
        Write-Warning "Source not found, skipping: $path"
        continue
    }

    $source = New-Object System.Xml.XmlDocument
    $source.PreserveWhitespace = $false
    $source.Load($path)

    $fileCount = 0
    foreach ($character in $source.SelectNodes('//NPCCharacter')) {
        $id = $character.GetAttribute('id')
        $occupation = $character.GetAttribute('occupation')

        if ([string]::IsNullOrWhiteSpace($id) -or
            $character.GetAttribute('is_hero') -eq 'true' -or
            $AllowedOccupations -notcontains $occupation) {
            $skipped++
            continue
        }

        $zombieId = "zombie_$id"
        $clone = $output.ImportNode($character, $true)

        $clone.SetAttribute('id', $zombieId)
        $clone.SetAttribute('name', ('Zombie ' + (Get-PlainName $character.GetAttribute('name'))))
        $clone.SetAttribute('occupation', 'Bandit')
        $clone.SetAttribute('culture', 'Culture.looters')

        # Belongs to the horde, not to a recruitment tree.
        $clone.RemoveAttribute('is_basic_troop')
        $clone.RemoveAttribute('upgrade_requires')

        $group = $clone.GetAttribute('default_group')
        if ($GroupRemap.ContainsKey($group)) {
            $clone.SetAttribute('default_group', $GroupRemap[$group])
        }

        # Zombies do not level up - they multiply. Dropping the node entirely
        # rather than emptying it: plenty of vanilla troops carry none at all.
        foreach ($targets in @($clone.SelectNodes('upgrade_targets'))) {
            [void] $clone.RemoveChild($targets)
        }

        # Own body property template so the runtime green tint cannot leak into
        # the shared vanilla templates (MBBodyProperty is a global game object).
        foreach ($face in @($clone.SelectNodes('face'))) {
            [void] $clone.RemoveChild($face)
        }
        $isFemale = $clone.GetAttribute('is_female') -eq 'true'
        $face = $output.CreateElement('face')
        $template = $output.CreateElement('face_key_template')
        $template.SetAttribute('value', $(if ($isFemale) { 'BodyProperty.zombie_female' } else { 'BodyProperty.zombie_male' }))
        [void] $face.AppendChild($template)
        [void] $clone.PrependChild($face)

        # Drop civilian outfits when a battle outfit exists - a zombie has no
        # civilian life.
        $equipments = $clone.SelectSingleNode('Equipments')
        if ($null -ne $equipments) {
            $battle = @($equipments.ChildNodes | Where-Object { $_.GetAttribute('equipmentType') -ne 'Civilian' })
            if ($battle.Count -gt 0) {
                foreach ($civilian in @($equipments.ChildNodes | Where-Object { $_.GetAttribute('equipmentType') -eq 'Civilian' })) {
                    [void] $equipments.RemoveChild($civilian)
                }
            }
        }

        $byId[$zombieId] = $clone
        $fileCount++
    }

    Write-Host ("{0,4} troops from {1}" -f $fileCount, $relative)
}

foreach ($clone in $byId.Values) {
    [void] $root.AppendChild($clone)
}

$settings = New-Object System.Xml.XmlWriterSettings
$settings.Indent = $true
$settings.IndentChars = "`t"
$settings.Encoding = New-Object System.Text.UTF8Encoding($false)

$resolved = [System.IO.Path]::GetFullPath($OutFile)
$writer = [System.Xml.XmlWriter]::Create($resolved, $settings)
try { $output.Save($writer) } finally { $writer.Dispose() }

Write-Host ""
Write-Host "Wrote $($byId.Count) zombie troops to $resolved ($skipped source entries skipped)."
