<#
.SYNOPSIS
    Generates a "zombie" race whose skin palette is green.

.DESCRIPTION
    Skin colour in Bannerlord is not a free RGB value but an offset into a per-race
    gradient, and that gradient IS plain XML: <skin_color_gradient_point point="r, g, b">
    in Native/ModuleData/skins.xml, an RGB multiplier on the skin texture.

    Editing the human gradient is not an option. The offset stored in a character's
    body properties is normalised to 0..1, so adding or replacing points shifts the
    skin tone of every vanilla NPC. A separate race keeps its own gradient and
    touches nothing else.

    MBObjectManager.MergeElements keys <race> by its id attribute (soln_skins.xsd,
    race_unique_attribute) and appends elements whose id is unknown, so a
    <race id="zombie"> arrives as a genuinely new race rather than merging into
    the human one.

    The race also needs a Monster named exactly like it - FaceGen resolves
    GetBaseMonsterFromRace via the race name - which is why
    ModuleData/monsters.xml defines "zombie" and "zombie_settlement".

.EXAMPLE
    pwsh -File tools\Generate-ZombieRace.ps1
#>
[CmdletBinding()]
param(
    [string] $GameDir = 'E:\SteamLibrary\steamapps\common\Mount & Blade II Bannerlord',
    [string] $OutFile = (Join-Path $PSScriptRoot '..\ZombiePlague\ModuleData\skins.xml'),

    # Multipliers applied to the brightness of each original tone. Green dominant,
    # blue lowest - raise $Green / lower $Red for a more toxic look.
    [double] $Red   = 0.55,
    [double] $Green = 0.95,
    [double] $Blue  = 0.45
)

$ErrorActionPreference = 'Stop'

$sourcePath = Join-Path $GameDir 'Modules\Native\ModuleData\skins.xml'
if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Native skins.xml not found at $sourcePath"
}

$source = New-Object System.Xml.XmlDocument
$source.Load($sourcePath)

$human = $source.SelectSingleNode('/skins/race[@id="human"]')
if ($null -eq $human) { throw 'No <race id="human"> in the native skins.xml.' }

$output = New-Object System.Xml.XmlDocument
[void] $output.AppendChild($output.CreateXmlDeclaration('1.0', 'utf-8', $null))
[void] $output.AppendChild($output.CreateComment(@"
 GENERATED by tools/Generate-ZombieRace.ps1 - do not edit by hand.

 A clone of the vanilla human race with a green skin gradient. Everything else
 (meshes, deform keys, hair, beards, tattoos, voices) is copied verbatim, so no
 new art assets are involved.

 Registered through ModuleData/project.mbproj (id soln_skins), not through
 SubModule.xml - skins.xml is an engine-level file, not an object-manager one.
"@))

$root = $output.CreateElement('skins')
[void] $output.AppendChild($root)

$race = $output.ImportNode($human, $true)
$race.SetAttribute('id', 'zombie')
[void] $root.AppendChild($race)

# The XML uses "0.90" regardless of the machine's locale, so parsing and
# formatting must both be invariant - on a German system "0.90" otherwise reads
# back as ninety and writes out as "0,9".
$invariant = [System.Globalization.CultureInfo]::InvariantCulture

$recoloured = 0
foreach ($point in $race.SelectNodes('.//skin_color_gradient_point')) {
    $parts = @($point.GetAttribute('point') -split ',' |
        ForEach-Object { [double]::Parse($_.Trim(), $invariant) })
    if ($parts.Count -ne 3) { continue }

    # Keep the original light-to-dark progression so the slider still gives variety,
    # just push every step towards green.
    $brightness = ($parts[0] + $parts[1] + $parts[2]) / 3.0
    $point.SetAttribute('point', [string]::Format($invariant, '{0:0.###}, {1:0.###}, {2:0.###}',
        [Math]::Min(1.0, $brightness * $Red),
        [Math]::Min(1.0, $brightness * $Green),
        [Math]::Min(1.0, $brightness * $Blue)))
    $recoloured++
}

$settings = New-Object System.Xml.XmlWriterSettings
$settings.Indent = $true
$settings.IndentChars = "`t"
$settings.Encoding = New-Object System.Text.UTF8Encoding($false)

$resolved = [System.IO.Path]::GetFullPath($OutFile)
$writer = [System.Xml.XmlWriter]::Create($resolved, $settings)
try { $output.Save($writer) } finally { $writer.Dispose() }

Write-Host "Recoloured $recoloured gradient points."
Write-Host "Wrote race 'zombie' to $resolved."
